FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./api /app/api

ENV PORT 80

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "${PORT}"]
