name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          cd src/
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/bedrock-access-gateway:${{ github.sha }}

      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/bedrock-access-gateway:${{ github.sha }}

      - name: Build the Docker_ecs image
        run: |
          cd src/
          docker build . --file Dockerfile_ecs --tag ghcr.io/${{ github.repository_owner }}/bedrock-access-gateway:${{ github.sha }}-ecs

      - name: Push the Docker_ecs image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/bedrock-access-gateway:${{ github.sha }}-ecs
